openapi: 3.0.3
info:
  title: Aftourism 运维监控接口
  version: '1.0.0'
  description: |-
    监控模块当前仅保留站点访问统计与 Redis 性能采集的后台任务，不再暴露系统指标上报接口。
    若后续需要新的监控 API，可在此文件内追加接口定义并同步更新聚合文档。
servers:
  - url: http://localhost:8080
    description: 本地开发环境
paths: {}
components: {}
