openapi: 3.0.3
info:
  title: 新闻管理API
  description: 新闻管理接口，包括创建、更新、删除和分页查询新闻等功能
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: 本地开发服务器

paths:
  /admin/news:
    post:
      summary: 创建新闻
      description: 创建一个新的新闻条目
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewsDTO'
      responses:
        '200':
          description: 创建成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultLong'
        '400':
          description: 请求参数错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultVoid'

  /admin/news/{id}:
    put:
      summary: 更新新闻
      description: 更新指定ID的新闻条目
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewsDTO'
      responses:
        '200':
          description: 更新成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultVoid'
        '400':
          description: 请求参数错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultVoid'
        '404':
          description: 新闻不存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultVoid'
    delete:
      summary: 删除新闻
      description: 逻辑删除指定ID的新闻条目
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 删除成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultVoid'
        '404':
          description: 新闻不存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultVoid'

  /admin/news/page:
    get:
      summary: 分页查询新闻
      description: 分页查询新闻列表，支持标题模糊匹配和状态筛选
      parameters:
        - name: current
          in: query
          required: true
          schema:
            type: integer
            minimum: 1
          description: 当前页码，从1开始
        - name: size
          in: query
          required: true
          schema:
            type: integer
            minimum: 1
            maximum: 100
          description: 每页条数
        - name: title
          in: query
          required: false
          schema:
            type: string
          description: 标题模糊匹配
        - name: status
          in: query
          required: false
          schema:
            type: integer
            minimum: 0
            maximum: 1
          description: 状态筛选
      responses:
        '200':
          description: 查询成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultPageInfoNewsVO'

components:
  schemas:
    NewsDTO:
      type: object
      required:
        - title
        - content
        - coverUrl
        - status
      properties:
        title:
          type: string
          description: 新闻标题
        content:
          type: string
          description: 新闻内容
        coverUrl:
          type: string
          description: 封面图URL
        author:
          type: string
          description: 作者
        status:
          type: integer
          minimum: 0
          maximum: 1
          description: 新闻状态，0-已下线，1-已发布
        publishTime:
          type: string
          format: date-time
          description: 发布时间
        viewCount:
          type: integer
          minimum: 0
          description: 浏览量
    
    NewsVO:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: 新闻ID
        title:
          type: string
          description: 新闻标题
        content:
          type: string
          description: 新闻内容
        coverUrl:
          type: string
          description: 封面图URL
        author:
          type: string
          description: 作者
        status:
          type: integer
          description: 新闻状态
        statusText:
          type: string
          description: 新闻状态文本
        publishTime:
          type: string
          format: date-time
          description: 发布时间
        viewCount:
          type: integer
          format: int64
          description: 浏览量
        createTime:
          type: string
          format: date-time
          description: 创建时间
        updateTime:
          type: string
          format: date-time
          description: 更新时间
    
    ResultVoid:
      type: object
      properties:
        code:
          type: integer
          description: 响应码
        msg:
          type: string
          description: 响应消息
        data:
          type: object
          description: 响应数据
          nullable: true
    
    ResultLong:
      type: object
      properties:
        code:
          type: integer
          description: 响应码
        msg:
          type: string
          description: 响应消息
        data:
          type: integer
          format: int64
          description: 响应数据
    
    ResultPageInfoNewsVO:
      type: object
      properties:
        code:
          type: integer
          description: 响应码
        msg:
          type: string
          description: 响应消息
        data:
          type: object
          properties:
            total:
              type: integer
              format: int64
              description: 总记录数
            list:
              type: array
              items:
                $ref: '#/components/schemas/NewsVO'
            pageNum:
              type: integer
              description: 当前页码
            pageSize:
              type: integer
              description: 每页条数
            size:
              type: integer
              description: 当前页记录数
            startRow:
              type: integer
              description: 起始行号
            endRow:
              type: integer
              description: 结束行号
            pages:
              type: integer
              description: 总页数
            prePage:
              type: integer
              description: 上一页页码
            nextPage:
              type: integer
              description: 下一页页码
            isFirstPage:
              type: boolean
              description: 是否第一页
            isLastPage:
              type: boolean
              description: 是否最后一页
            hasPreviousPage:
              type: boolean
              description: 是否有上一页
            hasNextPage:
              type: boolean
              description: 是否有下一页
            navigatePages:
              type: integer
              description: 导航页码数
            navigatepageNums:
              type: array
              items:
                type: integer
              description: 导航页码数组
            navigateFirstPage:
              type: integer
              description: 第一个导航页码
            navigateLastPage:
              type: integer
              description: 最后一个导航页码