openapi: 3.0.3
info:
  title: 门户收藏与活动留言接口
  description: "面向前台用户的收藏及活动留言功能接口说明"
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: 本地开发环境

paths:
  /portal/fav/{type}/{id}:
    post:
      summary: 添加收藏
      description: "用户登录后可对景区、场馆或活动执行收藏操作"
      parameters:
        - name: type
          in: path
          required: true
          schema:
            type: string
            enum: [SCENIC, VENUE, ACTIVITY]
          description: 收藏目标类型
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: 收藏目标ID
      responses:
        '200':
          description: 收藏成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultLong'
        '401':
          description: 未登录或登录失效
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultVoid'
    delete:
      summary: 取消收藏
      description: "取消已存在的收藏记录"
      parameters:
        - name: type
          in: path
          required: true
          schema:
            type: string
            enum: [SCENIC, VENUE, ACTIVITY]
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 取消成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultVoid'
        '401':
          description: 未登录或登录失效
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultVoid'

  /portal/fav/page:
    get:
      summary: 分页查询收藏列表
      description: "查询当前登录用户的收藏记录，可按类型过滤"
      parameters:
        - name: current
          in: query
          schema:
            type: integer
            minimum: 1
          description: 页码，默认1
        - name: size
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
          description: 每页条数，默认10
        - name: type
          in: query
          schema:
            type: string
            enum: [SCENIC, VENUE, ACTIVITY]
          description: 收藏类型过滤，留空表示全部
      responses:
        '200':
          description: 查询成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultPageInfoUserFavoriteVO'
        '401':
          description: 未登录或登录失效
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultVoid'

  /portal/activity/{id}/comment:
    post:
      summary: 发布活动留言
      description: "登录用户可对指定活动发布一级或二级留言"
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: 活动ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ActivityCommentCreateDTO'
      responses:
        '200':
          description: 留言成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultLong'
        '401':
          description: 未登录或登录失效
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultVoid'

  /portal/activity/{id}/comment/page:
    get:
      summary: 分页查询活动留言
      description: "按时间倒序获取活动的留言列表，可指定父留言ID分页查询回复"
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: current
          in: query
          schema:
            type: integer
            minimum: 1
          description: 页码，默认1
        - name: size
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
          description: 每页条数，默认10
        - name: parentId
          in: query
          schema:
            type: integer
            format: int64
          description: 父留言ID，不传则查询一级留言
      responses:
        '200':
          description: 查询成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultPageInfoActivityCommentVO'

components:
  schemas:
    ResultVoid:
      type: object
      properties:
        code:
          type: integer
        msg:
          type: string
        data:
          type: object
          nullable: true
    ResultLong:
      type: object
      properties:
        code:
          type: integer
        msg:
          type: string
        data:
          type: integer
          format: int64
    ResultPageInfoUserFavoriteVO:
      type: object
      properties:
        code:
          type: integer
        msg:
          type: string
        data:
          $ref: '#/components/schemas/PageInfoUserFavoriteVO'
    ResultPageInfoActivityCommentVO:
      type: object
      properties:
        code:
          type: integer
        msg:
          type: string
        data:
          $ref: '#/components/schemas/PageInfoActivityCommentVO'

    UserFavoriteVO:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: 收藏记录ID
        targetType:
          type: string
          enum: [SCENIC, VENUE, ACTIVITY]
          description: 收藏目标类型
        targetId:
          type: integer
          format: int64
          description: 收藏目标ID
        targetName:
          type: string
          description: 收藏目标名称
        targetCover:
          type: string
          description: 收藏目标封面图片地址
        createTime:
          type: string
          format: date-time
          description: 收藏时间

    ActivityCommentCreateDTO:
      type: object
      required: [content]
      properties:
        content:
          type: string
          description: 留言内容，最大500字
        parentId:
          type: integer
          format: int64
          nullable: true
          description: 父留言ID，不传表示一级留言

    ActivityCommentVO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        activityId:
          type: integer
          format: int64
        userId:
          type: integer
          format: int64
        userNickname:
          type: string
        userAvatar:
          type: string
        content:
          type: string
        parentId:
          type: integer
          format: int64
          nullable: true
        childCount:
          type: integer
          description: 子回复数量
        likeCount:
          type: integer
          description: 点赞数
        createTime:
          type: string
          format: date-time

    PageInfoUserFavoriteVO:
      type: object
      properties:
        total:
          type: integer
          format: int64
        list:
          type: array
          items:
            $ref: '#/components/schemas/UserFavoriteVO'
        pageNum:
          type: integer
        pageSize:
          type: integer
        size:
          type: integer
        startRow:
          type: integer
        endRow:
          type: integer
        pages:
          type: integer
        prePage:
          type: integer
          nullable: true
        nextPage:
          type: integer
          nullable: true
        isFirstPage:
          type: boolean
        isLastPage:
          type: boolean
        hasPreviousPage:
          type: boolean
        hasNextPage:
          type: boolean
        navigatePages:
          type: integer
        navigatepageNums:
          type: array
          items:
            type: integer
        navigateFirstPage:
          type: integer
        navigateLastPage:
          type: integer

    PageInfoActivityCommentVO:
      type: object
      properties:
        total:
          type: integer
          format: int64
        list:
          type: array
          items:
            $ref: '#/components/schemas/ActivityCommentVO'
        pageNum:
          type: integer
        pageSize:
          type: integer
        size:
          type: integer
        startRow:
          type: integer
        endRow:
          type: integer
        pages:
          type: integer
        prePage:
          type: integer
          nullable: true
        nextPage:
          type: integer
          nullable: true
        isFirstPage:
          type: boolean
        isLastPage:
          type: boolean
        hasPreviousPage:
          type: boolean
        hasNextPage:
          type: boolean
        navigatePages:
          type: integer
        navigatepageNums:
          type: array
          items:
            type: integer
        navigateFirstPage:
          type: integer
        navigateLastPage:
          type: integer
