openapi: 3.0.3
info:
  title: 后台 RBAC 管理接口
  version: '1.0.0'
  description: |-
    超级管理员用于维护后台管理员、门户用户及角色权限的接口。所有接口均需要通过 JWT（bearerAuth）认证，并依赖 `ROLE_ACCESS_*` 权限点。
servers:
  - url: http://localhost:8080
paths:
  /admin/rbac/admins/page:
    get:
      summary: 分页查询管理员
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: current
          schema:
            type: integer
            default: 1
        - in: query
          name: size
          schema:
            type: integer
            default: 10
        - in: query
          name: username
          schema:
            type: string
        - in: query
          name: realName
          schema:
            type: string
        - in: query
          name: status
          schema:
            type: integer
      responses:
        '200':
          description: 管理员分页列表
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultAdminAccountPage'
  /admin/rbac/admins/{id}:
    get:
      summary: 查询管理员详情
      security:
        - bearerAuth: []
      parameters:
        - in: path
          required: true
          name: id
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 管理员详情
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultAdminAccount'
    put:
      summary: 更新管理员
      security:
        - bearerAuth: []
      parameters:
        - in: path
          required: true
          name: id
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdminAccountUpdateRequest'
      responses:
        '200':
          description: 更新成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultVoid'
    delete:
      summary: 删除管理员
      security:
        - bearerAuth: []
      parameters:
        - in: path
          required: true
          name: id
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 删除成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultVoid'
  /admin/rbac/admins:
    post:
      summary: 新建管理员
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdminAccountCreateRequest'
      responses:
        '200':
          description: 新建成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultId'
  /admin/rbac/users/page:
    get:
      summary: 分页查询门户用户
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: current
          schema:
            type: integer
            default: 1
        - in: query
          name: size
          schema:
            type: integer
            default: 10
        - in: query
          name: username
          schema:
            type: string
        - in: query
          name: nickname
          schema:
            type: string
        - in: query
          name: status
          schema:
            type: integer
      responses:
        '200':
          description: 门户用户分页列表
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultPortalUserPage'
  /admin/rbac/users/{id}:
    put:
      summary: 调整门户用户角色或状态
      security:
        - bearerAuth: []
      parameters:
        - in: path
          required: true
          name: id
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PortalUserUpdateRequest'
      responses:
        '200':
          description: 更新成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultVoid'
  /admin/rbac/roles:
    get:
      summary: 查询角色权限列表
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 角色权限列表
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultRoleSummaryList'
  /admin/rbac/permissions/catalog:
    get:
      summary: 查询权限点目录
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 权限点目录
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultPermissionCatalog'
  /admin/rbac/roles/permissions:
    post:
      summary: 保存角色权限
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RolePermissionUpsertRequest'
      responses:
        '200':
          description: 保存成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultVoid'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    ResultVoid:
      type: object
      properties:
        code:
          type: integer
        msg:
          type: string
        data:
          nullable: true
    ResultId:
      type: object
      properties:
        code:
          type: integer
        msg:
          type: string
        data:
          type: integer
          format: int64
    ResultAdminAccountPage:
      type: object
      properties:
        code:
          type: integer
        msg:
          type: string
        data:
          $ref: '#/components/schemas/AdminAccountPage'
    ResultAdminAccount:
      type: object
      properties:
        code:
          type: integer
        msg:
          type: string
        data:
          $ref: '#/components/schemas/AdminAccount'
    ResultPortalUserPage:
      type: object
      properties:
        code:
          type: integer
        msg:
          type: string
        data:
          $ref: '#/components/schemas/PortalUserPage'
    ResultRoleSummaryList:
      type: object
      properties:
        code:
          type: integer
        msg:
          type: string
        data:
          type: array
          items:
            $ref: '#/components/schemas/RoleSummary'
    ResultPermissionCatalog:
      type: object
      properties:
        code:
          type: integer
        msg:
          type: string
        data:
          type: array
          items:
            $ref: '#/components/schemas/PermissionDefinition'
    AdminAccountPage:
      type: object
      properties:
        list:
          type: array
          items:
            $ref: '#/components/schemas/AdminAccount'
        pageNum:
          type: integer
        pageSize:
          type: integer
        total:
          type: integer
          format: int64
    AdminAccount:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        realName:
          type: string
        phone:
          type: string
        email:
          type: string
        status:
          type: integer
        superAdmin:
          type: boolean
        remark:
          type: string
        roleCodes:
          type: array
          items:
            type: string
        createTime:
          type: string
          format: date-time
        updateTime:
          type: string
          format: date-time
    AdminAccountCreateRequest:
      type: object
      required:
        - username
        - password
        - roleCodes
      properties:
        username:
          type: string
        password:
          type: string
        realName:
          type: string
        phone:
          type: string
        email:
          type: string
        roleCodes:
          type: array
          items:
            type: string
        superAdmin:
          type: boolean
        status:
          type: integer
        remark:
          type: string
    AdminAccountUpdateRequest:
      type: object
      properties:
        password:
          type: string
        realName:
          type: string
        phone:
          type: string
        email:
          type: string
        roleCodes:
          type: array
          items:
            type: string
        superAdmin:
          type: boolean
        status:
          type: integer
        remark:
          type: string
    PortalUserPage:
      type: object
      properties:
        list:
          type: array
          items:
            $ref: '#/components/schemas/PortalUser'
        pageNum:
          type: integer
        pageSize:
          type: integer
        total:
          type: integer
          format: int64
    PortalUser:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        nickname:
          type: string
        phone:
          type: string
        email:
          type: string
        roleCode:
          type: string
        status:
          type: integer
        createTime:
          type: string
          format: date-time
        updateTime:
          type: string
          format: date-time
    PortalUserUpdateRequest:
      type: object
      properties:
        roleCode:
          type: string
        status:
          type: integer
    RoleSummary:
      type: object
      properties:
        roleCode:
          type: string
        permissions:
          type: array
          items:
            $ref: '#/components/schemas/RolePermission'
    RolePermission:
      type: object
      properties:
        resourceKey:
          type: string
        action:
          type: string
        allow:
          type: boolean
        remark:
          type: string
    PermissionDefinition:
      type: object
      properties:
        key:
          type: string
        resourceKey:
          type: string
        action:
          type: string
        description:
          type: string
    RolePermissionUpsertRequest:
      type: object
      required:
        - roleCode
        - permissions
      properties:
        roleCode:
          type: string
        permissions:
          type: array
          items:
            $ref: '#/components/schemas/RolePermissionItem'
    RolePermissionItem:
      type: object
      properties:
        resourceKey:
          type: string
        action:
          type: string
        allow:
          type: boolean
        remark:
          type: string
