openapi: 3.0.3
info:
  title: 后台回收站接口
  description: "提供软删除数据的统一查看、恢复与彻底删除能力"
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: 本地开发环境

paths:
  /admin/recycle/page:
    get:
      summary: 分页查询回收站数据
      description: "按业务类型查询已软删除的数据，支持关键词与时间范围过滤"
      parameters:
        - name: type
          in: query
          required: true
          schema:
            type: string
            enum: [NEWS, NOTICE, SCENIC, VENUE, ACTIVITY]
          description: 数据类型
        - name: keyword
          in: query
          schema:
            type: string
          description: 标题或名称关键词
        - name: startTime
          in: query
          schema:
            type: string
            format: date-time
          description: 删除时间起始（包含）
        - name: endTime
          in: query
          schema:
            type: string
            format: date-time
          description: 删除时间结束（包含）
        - name: current
          in: query
          schema:
            type: integer
            minimum: 1
          description: 页码，默认 1
        - name: size
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
          description: 每页条数，默认 10
      responses:
        '200':
          description: 查询成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultPageInfoRecycleItemVO'
  /admin/recycle/{type}/{id}/restore:
    put:
      summary: 恢复回收站记录
      description: "将指定记录恢复为有效状态"
      parameters:
        - name: type
          in: path
          required: true
          schema:
            type: string
            enum: [NEWS, NOTICE, SCENIC, VENUE, ACTIVITY]
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 恢复成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultVoid'
  /admin/recycle/{type}/{id}:
    delete:
      summary: 彻底删除记录
      description: "从数据库物理删除已软删除的数据"
      parameters:
        - name: type
          in: path
          required: true
          schema:
            type: string
            enum: [NEWS, NOTICE, SCENIC, VENUE, ACTIVITY]
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 删除成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultVoid'

components:
  schemas:
    ResultVoid:
      type: object
      properties:
        code:
          type: integer
        msg:
          type: string
        data:
          nullable: true
    ResultPageInfoRecycleItemVO:
      type: object
      properties:
        code:
          type: integer
        msg:
          type: string
        data:
          $ref: '#/components/schemas/PageInfoRecycleItemVO'
    PageInfoRecycleItemVO:
      type: object
      properties:
        pageNum:
          type: integer
        pageSize:
          type: integer
        total:
          type: integer
          format: int64
        list:
          type: array
          items:
            $ref: '#/components/schemas/RecycleItemVO'
    RecycleItemVO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        type:
          type: string
          enum: [NEWS, NOTICE, SCENIC, VENUE, ACTIVITY]
        title:
          type: string
        deletedTime:
          type: string
          format: date-time
        operator:
          type: string
          nullable: true
        extraInfo:
          type: string
          nullable: true
